// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScuoloaDbApp.Server.Data;

#nullable disable

namespace ScuoloaDbApp.Server.Migrations
{
    [DbContext(typeof(Scuola2022dbContext))]
    [Migration("20230112123809_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ScuoloaDbApp.Shared.Classe", b =>
                {
                    b.Property<string>("Sigla")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicazione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Sigla");

                    b.ToTable("Classi");
                });

            modelBuilder.Entity("ScuoloaDbApp.Shared.ClassiStudenti", b =>
                {
                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroStudenti")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ubicazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sigla");

                    b.ToTable("ClassiStudenti");
                });

            modelBuilder.Entity("ScuoloaDbApp.Shared.Studente", b =>
                {
                    b.Property<int>("Matricola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClasseSigla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diplomato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Matricola");

                    b.HasIndex("ClasseSigla");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ScuoloaDbApp.Shared.Studente", b =>
                {
                    b.HasOne("ScuoloaDbApp.Shared.Classe", "Classe")
                        .WithMany("Studenti")
                        .HasForeignKey("ClasseSigla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("ScuoloaDbApp.Shared.Classe", b =>
                {
                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
